export const STORAGE_KEYS = {
    SOURCES: "SOURCES",
    ARTICLE_DETAIL:'ARTICLE_DETAIL',
    SOURCE_LIST:'SOURCE_LIST'
}

export const DATE_FORMATE='YYYY/MM/DD';
export const DATE_FORMATE2='YYYY-MM-DD';